services:
  - type: web
    name: ac2fl
    env: docker
    plan: free
    repo: https://github.com/ales230/ac2fl
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: mysql://root@host:3306/bdl-ac2fl
