services:
  - name: ac2fl
    type: web
    runtime: php
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ac2fl-db
          property: connectionString
databases:
  - name: ac2fl-db
    databaseName: ac2fl
    user: admin
